name: FLCombatLog
version: '${project.version}'
main: com.missyu.dev.flcombatlog.FLCombatLog
api-version: 1.20
depend:
  - Citizens
authors: [ finalLy ]
description: A combat log plugin for Beit Shamai server.
commands:
  flcombatlog:
    usage: /<command> <reload>
    description: A command to control the FLCombatLog system.
    aliases:
      - flcl
    permission: flcombatlog.reload